ykzts/node-xmlhttprequest

package.json
[diff](https://github.com/mochajs/mocha/compare/1.13.0...2.3.4)
=> Upgrade Mocha

lib/index.js
node require("w3c-xmlhttprequest") broke with Error: Cannot find module 'formdata'
=> index.js require formdata point to formdata.js

lib/browser.js, package.json
ref: https://github.com/substack/browserify-handbook/blob/e21ccd34f63be30baa387fa846874602d6150c08/readme.markdown#browser-field
=> Don't load from the web browser

README.md
=> Change to latest the W3C spec URI [ci skip]

.github/workflows/node.js.yml
=> ci(github-actions): introduce github actions

.github/workflows/codeql-analysis.yml
=> ci(codeql): introduce code scanning

.github/dependabot.yml
=> ci(dependabot): add dependabot config

package.json, src/utils.js, test/xmlhttprequest.js
=> refactor: replace to URL

src/xmlhttprequest.ts, test/integration/xmlhttprequest.ts
=> fix(xmlhttprequest): add line break for getAllResponseHeaders()

.github/linters/.eslintrc.js, .github/workflows/linter.yml, .github/workflows/node.js.yml
=> ci(super-linter): introduce super-linter

src/xmlhttprequest.ts, test/integration/xmlhttprequest.ts
=> fix(xmlhttprequest): catch errors

src/xmlhttprequest.ts, test/integration/xmlhttprequest.ts
=> fix(xmlhttprequest): replace to req.destroy from req.abort

package.json, yarn.lock
=> chore: introduce commitlint

.github/workflows/npm-publish.yml, .github/workflows/release.yml, package.json, yarn.lock
=> ci(github-actions): introduce standard-version

package.json
=> feat(meta): add keywords field to package.json

src/html/eventhandler.ts, src/xmlhttprequest.ts, src/xmlhttprequesteventtarget.ts, test/integration/xmlhttprequest.ts
=> fix(xmlhttprequest): support object property

src/xmlhttprequest.ts, test/integration/xmlhttprequest.ts
=> fix(xmlhttprequest): throw exception when invalid state

src/dom/eventtarget.ts, test/integration/xmlhttprequest.ts
=> fix(xmlhttprequest): add support EventListenerObject

src/xmlhttprequest.ts, test/integration/xmlhttprequest.ts
=> fix(xmlhttprequest): add support xhr.responseURL

husky.config.js, package.json, yarn.lock
=> ci(lint-staged): introduce lint-staged

src/progressevent.ts, src/xmlhttprequest.ts
=> feat(xhr): supports xhr.timeout
